export const classes = {
  background: {
    dark: "bg-dark-700",
    base: "bg-dark-500",
    light: "bg-dark-300",
    hoverDark: "hover:bg-dark-700",
    hoverBase: "hover:bg-dark-500",
    hoverLight: "hover:bg-dark-300",
    hoverDarkInverted: "hover:bg-light-600",
    hoverBaseInverted: "hover:bg-light-500",
    hoverLightInverted: "hover:bg-light-300",
    darkInverted: "bg-light-600",
    baseInverted: "bg-light-500",
    lightInverted: "bg-light-300",
  },
  textBase: "text-light-400",
  textDark: "text-light-500",
  textWhite: "text-light-100",
  textAccent: "text-aquamarine-500",
  textBaseInverted: "text-dark-700",
  textHover: "hover:text-light-500",
  textHoverInverted: "hover:text-dark-300",
  placeholder: "placeholder-light-300",
  border: "border-dark-300",
  borderHover: "hover:border-dark-300",
  borderDark: "border-light-400",
};
